[variables]
NIXPACKS_PHP_ROOT_DIR = "/app"

[phases.setup]
nixPkgs = ["php82"]

[phases.install]
cmds = [
  "mkdir -p /app/.php-extensions",
  "echo extension=mysqli > /app/.php-extensions/mysqli.ini",
  "echo extension=pdo_mysql > /app/.php-extensions/pdo_mysql.ini"
]

[start]
cmd = "php -d extension=mysqli -d extension=pdo_mysql -S 0.0.0.0:$PORT router.php"
